# Generated by Django 2.2.7 on 2022-01-21 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import timetracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', django_jalali.db.models.jDateField(null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_friday', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'holiday_days',
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='شروع')),
                ('end', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('w_time', models.TimeField(blank=True, editable=False, null=True, verbose_name='مدت زمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'db_table': 'work_records',
            },
        ),
        migrations.CreateModel(
            name='VocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(choices=[('روزانه', 'روزانه'), ('ساعتی', 'ساعتی')], max_length=25, null=True, verbose_name='نوع مرخصی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('start', django_jalali.db.models.jDateTimeField(verbose_name='شروع')),
                ('end', django_jalali.db.models.jDateTimeField(verbose_name='پایان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست مرخصی',
                'verbose_name_plural': 'درخواست های مرخصی',
                'db_table': 'vocation_requests',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=timetracker.models.profile_image, verbose_name='عکس پروفایل')),
                ('saturday_time', models.IntegerField(default=0, null=True, verbose_name='تایم کاری شنبه')),
                ('sunday_time', models.IntegerField(default=0, null=True, verbose_name='تایم کاری یکشنبه')),
                ('monday_time', models.IntegerField(default=0, null=True, verbose_name='تایم کاری دوشنبه')),
                ('tuesday_time', models.IntegerField(default=0, null=True, verbose_name='تایم کاری سه شنبه')),
                ('wednesday_time', models.IntegerField(default=0, null=True, verbose_name='تایم کاری چهارشنبه')),
                ('thursday_time', models.IntegerField(default=0, null=True, verbose_name='تایم کاری پنجشنبه')),
                ('friday_time', models.IntegerField(default=0, null=True, verbose_name='تایم کاری جمعه')),
                ('vocation_in_month', models.IntegerField(blank=True, null=True, verbose_name='تعداد ساعت مرخصی در ماه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
                'db_table': 'user_profile',
            },
        ),
    ]
