# Generated by Django 3.0.4 on 2022-01-22 11:33

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='start',
            field=django_jalali.db.models.jDateTimeField(verbose_name='شروع'),
        ),
    ]
