# Generated by Django 3.0.4 on 2022-05-03 11:37

from django.db import migrations, models
import timetracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_auto_20220122_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses_image',
            field=models.ImageField(blank=True, null=True, upload_to=timetracker.models.courses_image_func, verbose_name='عکس انتخاب واحد'),
        ),
    ]
