# Generated by Django 3.0.4 on 2022-05-04 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetracker', '0003_userprofile_courses_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvailibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('1', 'saturday'), ('2', 'sunday'), ('3', 'monday'), ('4', 'tuesday'), ('5', 'wednesday'), ('6', 'thursday'), ('7', 'friday')], max_length=25, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availibilities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
