# Generated by Django 3.0.4 on 2022-08-17 11:34

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_auto_20220505_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'برنامه رکورد',
                'verbose_name_plural': 'برنامه های رکورد',
                'db_table': 'recorded_app',
            },
        ),
        migrations.CreateModel(
            name='RecordedWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='نام')),
                ('domain', models.CharField(max_length=100, verbose_name='آدرس دامنه')),
            ],
            options={
                'verbose_name': 'سایت رکورد',
                'verbose_name_plural': 'سایت های رکورد',
                'db_table': 'recorded_website',
            },
        ),
        migrations.CreateModel(
            name='AppRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', django_jalali.db.models.jDateTimeField(verbose_name='شروع')),
                ('end', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('w_time', models.TimeField(blank=True, editable=False, null=True, verbose_name='مدت زمان')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='timetracker.RecordedApp')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='timetracker.RecordedWebsite')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_records', to='timetracker.WorkRecord')),
            ],
            options={
                'verbose_name': 'زمان کاری با برنامه',
                'verbose_name_plural': 'زمان کاری با برنامه',
                'db_table': 'app_record',
            },
        ),
    ]
