# Generated by Django 3.0.4 on 2022-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0006_apprecord_recordedapp_recordedwebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_inactive_time', models.IntegerField(default=30, verbose_name='حداکثر زمان غیر فعالیت(دقیقه)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='recordedapp',
            options={'verbose_name': 'برنامه', 'verbose_name_plural': 'ردیابی-برنامه ها'},
        ),
        migrations.AlterModelOptions(
            name='recordedwebsite',
            options={'verbose_name': 'سایت', 'verbose_name_plural': 'ردیابی-سایت ها'},
        ),
    ]
