# Generated by Django 3.0.4 on 2022-08-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0007_auto_20220817_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'تنظمیات سیستم', 'verbose_name_plural': 'تنظمیات سیستم'},
        ),
        migrations.AlterModelTable(
            name='systemconfig',
            table='system_config',
        ),
    ]
