# Generated by Django 3.0.4 on 2022-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0008_auto_20220817_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedapp',
            name='is_browser',
            field=models.BooleanField(default=False, verbose_name='مرورگر'),
        ),
    ]
