# Generated by Django 3.0.4 on 2022-08-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0009_recordedapp_is_browser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprecord',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='timetracker.RecordedWebsite'),
        ),
    ]
