# Generated by Django 3.0.4 on 2022-08-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0010_auto_20220822_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprecord',
            name='end',
        ),
        migrations.RemoveField(
            model_name='apprecord',
            name='start',
        ),
    ]
