# Generated by Django 3.0.4 on 2022-08-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0011_auto_20220822_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprecord',
            name='w_time',
        ),
    ]
