# Generated by Django 3.0.4 on 2022-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0012_remove_apprecord_w_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprecord',
            name='w_time',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='مدت زمان به ثانیه'),
        ),
    ]
