# Generated by Django 3.0.4 on 2022-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0013_apprecord_w_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='inactive_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='زمان غیر فعالیت'),
        ),
    ]
