# Generated by Django 3.0.4 on 2022-08-24 05:13

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0014_workrecord_inactive_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordInactiveTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', django_jalali.db.models.jDateTimeField(verbose_name='شروع')),
                ('end', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_times', to='timetracker.WorkRecord')),
            ],
            options={
                'verbose_name': 'زمان کاری با برنامه',
                'verbose_name_plural': 'زمان کاری با برنامه',
                'db_table': 'record_inactive_time',
            },
        ),
    ]
