# Generated by Django 3.0.4 on 2022-08-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0015_recordinactivetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedapp',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='recorded_apps/', verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='recordedwebsite',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='recorded_websites/', verbose_name='آیکون'),
        ),
    ]
