# Generated by Django 3.0.4 on 2022-08-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0016_auto_20220824_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordinactivetime',
            options={'verbose_name': 'زمان غیرفعال', 'verbose_name_plural': 'زمان های غیرفعال '},
        ),
        migrations.AddField(
            model_name='workrecord',
            name='sum_words',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد کلمات'),
        ),
    ]
