# Generated by Django 3.0.4 on 2022-08-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0017_auto_20220828_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
