# Generated by Django 3.0.4 on 2022-08-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0018_workrecord_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='p_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_records', to='timetracker.WorkRecord'),
        ),
    ]
