# Generated by Django 3.0.4 on 2023-04-06 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetracker', '0019_workrecord_p_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_text', models.TextField(blank=True, null=True, verbose_name='متن خطا')),
                ('json_text', models.TextField(blank=True, null=True, verbose_name='جیسون ارسالی')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='timetracker.UserError')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خطا',
                'verbose_name_plural': 'خطاهای کاربران',
                'db_table': 'user_errors',
            },
        ),
    ]
