# Generated by Django 3.0.4 on 2023-04-07 21:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0020_usererror'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='last_updated',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
