# Generated by Django 4.2.5 on 2023-10-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0021_workrecord_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_person',
            field=models.BooleanField(default=False, verbose_name='کارمند حضوری'),
        ),
    ]
