# Generated by Django 3.0.4 on 2024-07-26 14:37

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0022_userprofile_in_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='timetracker.WorkRecord')),
            ],
            options={
                'verbose_name': 'لاگ تغییر ساعت کاری',
                'verbose_name_plural': 'لاگ تغییرات ساعت کاری',
                'db_table': 'record_change_log',
            },
        ),
    ]
