# Generated by Django 5.2 on 2025-04-20 19:30

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0022_userprofile_in_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='timetracker.workrecord')),
            ],
            options={
                'verbose_name': 'لاگ کاری',
                'verbose_name_plural': 'لاگ کاری',
                'db_table': 'record_log',
            },
        ),
    ]
