# Generated by Django 4.2.20 on 2025-04-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0023_recordchangelog'),
        ('timetracker', '0023_recordlog'),
    ]

    operations = [
    ]
