# Generated by Django 4.2.20 on 2025-12-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0023_recordlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='allowed_inactive_time_in_person',
            field=models.IntegerField(default=30, verbose_name='حداکثر زمان غیر فعالیت کارمندان حضوری(دقیقه)'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='allowed_inactive_time',
            field=models.IntegerField(default=30, verbose_name='حداکثر زمان غیر فعالیت کارمندان غیرحضوری(دقیقه)'),
        ),
    ]
