# Generated by Django 4.2.20 on 2025-12-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0024_merge_0023_recordchangelog_0023_recordlog'),
        ('timetracker', '0024_systemconfig_allowed_inactive_time_in_person_and_more'),
    ]

    operations = [
    ]
