# Generated by Django 4.2.20 on 2025-12-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0025_merge_20251222_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordChangeLog',
        ),
    ]
