# Generated by Django 4.2.20 on 2025-12-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0026_delete_recordchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inactive_time_delete_min',
            field=models.IntegerField(default=0, verbose_name=' حذف غیرفعال بیشتر از n دقیقه'),
        ),
    ]
