# Generated by Django 5.2.17 on 2026-08-06 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleagues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام پروژه")),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="بدون http",
                        max_length=200,
                        verbose_name="دامنه",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4183F2", max_length=7, verbose_name="رنگ"
                    ),
                ),
                (
                    "project_types",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نوع پروژه"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "فعال"), ("inactive", "غیرفعال")],
                        default="active",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان غیرفعال\u200cسازی"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=14,
                        null=True,
                        verbose_name="مبلغ قرارداد",
                    ),
                ),
                (
                    "contract_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="شروع قرارداد"
                    ),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="پایان قرارداد"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="نام کارفرما"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="تلفن کارفرما"
                    ),
                ),
                ("wp_api_url", models.URLField(blank=True, verbose_name="WP API URL")),
                (
                    "wp_username",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="WP Username"
                    ),
                ),
                (
                    "wp_app_password",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="WP App Password"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to="colleagues.colleague",
                        verbose_name="مسئول پروژه",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="colleagues.colleague",
                        verbose_name="تیم",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
                "ordering": ["status", "name"],
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                ("url", models.URLField(blank=True, verbose_name="آدرس")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام کاربری"
                    ),
                ),
                (
                    "password_enc",
                    models.TextField(
                        blank=True, verbose_name="پسورد رمزنگاری\u200cشده"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="یادداشت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی",
                "verbose_name_plural": "دسترسی\u200cها",
                "ordering": ["title"],
            },
        ),
    ]
