# Generated by Django 5.2.17 on 2026-08-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_alter_project_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="track_keyword_rank",
            field=models.BooleanField(
                default=False,
                help_text="با فعال\u200cبودن، افزونهٔ مرورگر جایگاهِ این دامنه را در نتایجِ گوگل ثبت می\u200cکند.",
                verbose_name="بررسی رتبه کلمات کلیدی",
            ),
        ),
    ]
