# Generated by Django 5.2.17 on 2026-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_track_keyword_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/projects/", verbose_name="لوگو"
            ),
        ),
    ]
