# Generated by Django 5.2.17 on 2026-08-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleagues", "0004_colleague_birth_date_colleague_worktracker_username"),
        ("projects", "0004_project_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="personal_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_projects",
                to="colleagues.colleague",
                verbose_name="مالکِ پروژه\u200cی شخصی",
            ),
        ),
    ]
