# Generated by Django 5.2.17 on 2026-08-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_backfill_personal_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="اولویت"
            ),
        ),
    ]
