# Generated by Django 5.2.17 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_deleted_at_project_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content_hourly_rate",
            field=models.BigIntegerField(
                default=0, verbose_name="نرخِ ساعتیِ تولید محتوا (ریال)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="content_word_rate",
            field=models.BigIntegerField(
                default=0, verbose_name="نرخِ هر کلمهٔ تولید محتوا (ریال)"
            ),
        ),
    ]
