# Generated by Django 5.2.17 on 2026-08-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="تاریخ (میلادی)")),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official", "رسمی"),
                            ("religious", "مذهبی"),
                            ("occasion", "مناسبت"),
                        ],
                        default="official",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                ("is_off", models.BooleanField(default=True, verbose_name="تعطیل است")),
            ],
            options={
                "verbose_name": "تعطیلی",
                "verbose_name_plural": "تعطیلات",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=120, verbose_name="عمل")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "changes",
                    models.JSONField(blank=True, default=dict, verbose_name="تغییرات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ فعالیت",
                "verbose_name_plural": "لاگ فعالیت\u200cها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_activi_content_1a7154_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/", verbose_name="فایل"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام اصلی"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="حجم (بایت)"),
                ),
                (
                    "mime",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="نوع MIME"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="عنوان"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آپلودکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیوست",
                "verbose_name_plural": "پیوست\u200cها",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_attach_content_d3cac2_idx",
                    )
                ],
            },
        ),
    ]
