# Generated by Django 5.2.17 on 2026-08-10 19:39

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_stamp_orgs_seed_roles"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table",
                    models.CharField(
                        choices=[
                            ("tasks", "تسک\u200cها"),
                            ("projects", "پروژه\u200cها"),
                            ("colleagues", "همکاران"),
                        ],
                        max_length=12,
                        verbose_name="جدول",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("page", "صفحه\u200cی خودش"),
                            ("dashboard", "داشبورد"),
                        ],
                        max_length=10,
                        verbose_name="محل نمایش",
                    ),
                ),
                (
                    "keys",
                    models.JSONField(
                        blank=True, default=list, verbose_name="کلیدهای ستون (به ترتیب)"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="سازمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمِ ستون\u200cها",
                "verbose_name_plural": "تنظیمِ ستون\u200cها",
                "base_manager_name": "all_objects",
                "unique_together": {("organization", "table", "scope")},
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
