# Generated by Django 5.2.17 on 2026-08-07 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleagues", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="عنوان بابت"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#8FA0B8", max_length=7, verbose_name="رنگ"
                    ),
                ),
                (
                    "is_salary",
                    models.BooleanField(default=False, verbose_name="مربوط به حقوق"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "بابت",
                "verbose_name_plural": "بابت\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام حساب")),
                (
                    "bank",
                    models.CharField(blank=True, max_length=60, verbose_name="بانک"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4183F2", max_length=7, verbose_name="رنگ"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="شماره کارت/حساب"
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=16,
                        verbose_name="مانده\u200cی اولیه",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب بانکی",
                "verbose_name_plural": "حساب\u200cهای بانکی",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="سال شمسی")),
                ("month", models.PositiveIntegerField(verbose_name="ماه شمسی")),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=16,
                        verbose_name="پرداخت\u200cشده",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="یادداشت"
                    ),
                ),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="colleagues.colleague",
                        verbose_name="همکار",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "حقوق",
                "verbose_name_plural": "حقوق\u200cها",
                "ordering": ["-year", "-month"],
                "unique_together": {("colleague", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="PayrollItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="عنوان")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=16, verbose_name="مبلغ"
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.payroll",
                        verbose_name="حقوق",
                    ),
                ),
            ],
            options={
                "verbose_name": "جزء حقوق",
                "verbose_name_plural": "اجزای حقوق",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "time",
                    models.CharField(blank=True, max_length=8, verbose_name="ساعت"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="شرح سند"
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=16, verbose_name="واریز"
                    ),
                ),
                (
                    "withdrawal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=16,
                        verbose_name="برداشت",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=16,
                        null=True,
                        verbose_name="مانده",
                    ),
                ),
                (
                    "user_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات کاربر (اکسل)"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "import_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="هش تشخیص تکراری",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.bankaccount",
                        verbose_name="حساب",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.category",
                        verbose_name="بابت",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["bank_account", "date"],
                        name="finance_tra_bank_ac_387797_idx",
                    ),
                    models.Index(
                        fields=["project", "category"],
                        name="finance_tra_project_7282f3_idx",
                    ),
                ],
            },
        ),
    ]
