# Generated by Django 5.2.17 on 2026-08-08 21:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_phone_role"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["name"],
                "verbose_name": "حساب بانکی",
                "verbose_name_plural": "حساب\u200cهای بانکی",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["order", "name"],
                "verbose_name": "بابت",
                "verbose_name_plural": "بابت\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="payroll",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-year", "-month"],
                "verbose_name": "حقوق",
                "verbose_name_plural": "حقوق\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-date", "-id"],
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
            },
        ),
        migrations.AlterModelManagers(
            name="bankaccount",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="payroll",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="transaction",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.organization",
                verbose_name="سازمان",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.organization",
                verbose_name="سازمان",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.organization",
                verbose_name="سازمان",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.organization",
                verbose_name="سازمان",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=80, verbose_name="عنوان بابت"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("organization", "name")},
        ),
    ]
