# Generated by Django 5.2.17 on 2026-08-12 16:34

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_membership_role"),
        ("finance", "0002_alter_bankaccount_options_alter_category_options_and_more"),
        ("projects", "0003_project_track_keyword_rank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="شماره فاکتور",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="تاریخ ثبت فاکتور")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات فاکتور"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="سازمان",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور",
                "verbose_name_plural": "فاکتورها",
                "ordering": ["-issue_date", "-number", "-id"],
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=12, verbose_name="تعداد"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=16,
                        verbose_name="مبلغ واحد",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=16,
                        verbose_name="مالیات",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=16, verbose_name="تخفیف"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_lines",
                        to="finance.category",
                        verbose_name="بابت",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.invoice",
                        verbose_name="فاکتور",
                    ),
                ),
            ],
            options={
                "verbose_name": "ردیف فاکتور",
                "verbose_name_plural": "ردیف\u200cهای فاکتور",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("organization", "number"), name="uniq_invoice_number_per_org"
            ),
        ),
    ]
