# Generated by Django 5.2.17 on 2026-08-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleagues", "0003_remove_colleague_rate_per_task_and_more"),
        ("finance", "0003_invoice_invoiceline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="colleague",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salary_categories",
                to="colleagues.colleague",
                verbose_name="همکار (حقوق)",
            ),
        ),
    ]
