# Generated by Django 5.2.17 on 2026-08-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_backfill_salary_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-date", "id"],
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
            },
        ),
    ]
