# Generated by Django 5.2.17 on 2026-08-16 23:02
# ویرایش‌شده: ابتدا M2M ساخته می‌شود و داده‌ی category به categories کپی می‌شود،
# سپس فیلدِ تک‌انتخابیِ category حذف می‌شود (تا داده از دست نرود).

from django.conf import settings
from django.db import migrations, models


def copy_category_to_categories(apps, schema_editor):
    Transaction = apps.get_model("finance", "Transaction")
    for t in Transaction.objects.exclude(category__isnull=True).iterator():
        t.categories.add(t.category_id)


def reverse_copy(apps, schema_editor):
    # برگشت: اولین بابتِ هر تراکنش را به فیلدِ تکیِ category برگردان
    Transaction = apps.get_model("finance", "Transaction")
    for t in Transaction.objects.all().iterator():
        first = t.categories.first()
        if first:
            t.category_id = first.id
            t.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_membership_role"),
        ("finance", "0006_alter_transaction_options"),
        ("projects", "0006_backfill_personal_projects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="income_source",
            field=models.CharField(
                choices=[
                    ("transaction", "از تراکنش‌ها"),
                    ("invoice", "از فاکتورها"),
                ],
                default="transaction",
                max_length=12,
                verbose_name="منبعِ درآمد",
            ),
        ),
        # ۱) M2M جدید را بساز (category هنوز هست)
        migrations.AddField(
            model_name="transaction",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="transactions",
                to="finance.category",
                verbose_name="بابت‌ها",
            ),
        ),
        # ۲) داده‌ی تک‌انتخابی → چندانتخابی
        migrations.RunPython(copy_category_to_categories, reverse_copy),
        # ۳) حالا فیلدِ قدیمی و ایندکسش را حذف کن
        migrations.RemoveIndex(
            model_name="transaction",
            name="finance_tra_project_7282f3_idx",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["project", "date"], name="finance_tra_project_f3fc61_idx"
            ),
        ),
    ]
