# Generated by Django 5.2.17 on 2026-09-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_transactionsplit"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="receipts/",
                verbose_name="رسیدِ پرداخت",
            ),
        ),
    ]
