# Generated by Django 5.2.17 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_invoice_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="sheba",
            field=models.CharField(
                blank=True,
                help_text="بدونِ IR هم مجاز است",
                max_length=34,
                verbose_name="شماره شبا",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="show_on_invoice",
            field=models.BooleanField(
                default=False, verbose_name="نمایش زیرِ فاکتورِ مشتری"
            ),
        ),
    ]
