# Generated by Django 5.2.17 on 2026-09-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_bankaccount_sheba_bankaccount_show_on_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="sheba",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="show_on_invoice",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="receipt",
        ),
    ]
