# Generated by Django 5.2.17 on 2026-09-07 19:28

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_organization_custom_head_html"),
        ("finance", "0011_remove_bankaccount_sheba_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("body", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "done",
                    models.BooleanField(default=False, verbose_name="رسیدگی\u200cشده"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="سازمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشتِ حسابداری",
                "verbose_name_plural": "یادداشت\u200cهای حسابداری",
                "ordering": ["-date", "-id"],
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
