# Generated by Django 5.2.17 on 2026-08-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_bootstrap_default_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, verbose_name="شماره تماس"
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, verbose_name="کلید")),
                ("name", models.CharField(max_length=60, verbose_name="نام نقش")),
                (
                    "perms",
                    models.JSONField(
                        blank=True, default=list, verbose_name="دسترسی\u200cها"
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=False, verbose_name="پیش\u200cفرض"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="accounts.organization",
                        verbose_name="سازمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "نقش",
                "verbose_name_plural": "نقش\u200cها",
                "ordering": ["name"],
                "unique_together": {("organization", "key")},
            },
        ),
    ]
