# Generated by Django 5.2.17 on 2026-08-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_stamp_orgs_seed_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام (برای خودت)"
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="هشِ کلید",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        verbose_name="پیشوندِ نمایشی",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین استفاده"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="accounts.organization",
                        verbose_name="سازمان",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "توکنِ API",
                "verbose_name_plural": "توکن\u200cهای API",
                "ordering": ["-created_at"],
            },
        ),
    ]
