# Generated by Django 5.2.17 on 2026-08-11 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="برای دعوتِ شماره\u200cای که هنوز ثبت\u200cنام نکرده — تا ثبت\u200cنامش با همین دعوت وصل شود.",
                max_length=20,
                verbose_name="شماره تماس",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
