# Generated by Django 5.2.17 on 2026-08-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_invite_phone_alter_invite_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "مالک"),
                    ("admin", "مدیر"),
                    ("manager", "سرپرست"),
                    ("member", "عضو"),
                    ("viewer", "ناظر"),
                ],
                default="member",
                max_length=32,
                verbose_name="نقش",
            ),
        ),
    ]
