# Generated by Django 5.2.17 on 2026-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_membership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="custom_head_html",
            field=models.TextField(
                blank=True, verbose_name="کدهای اضافه (قبل از </head>)"
            ),
        ),
    ]
