# Generated by Django 5.2.17 on 2026-08-07 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0002_alter_task_planned_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("date_from", models.DateField(verbose_name="از تاریخ")),
                ("date_to", models.DateField(verbose_name="تا تاریخ")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "پیش\u200cنویس"), ("final", "نهایی")],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "public_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="توکن عمومی",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="لینک عمومی فعال"),
                ),
                (
                    "visible_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="فیلدهای قابل\u200cنمایش به مشتری",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش",
                "verbose_name_plural": "گزارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "override_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان (override)"
                    ),
                ),
                (
                    "override_done_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ انجام (override)"
                    ),
                ),
                (
                    "override_description",
                    models.TextField(blank=True, verbose_name="توضیحات (override)"),
                ),
                (
                    "manual_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="نوع (ردیف دستی)"
                    ),
                ),
                (
                    "manual_url",
                    models.URLField(blank=True, verbose_name="لینک (ردیف دستی)"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reports.report",
                        verbose_name="گزارش",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_items",
                        to="tasks.task",
                        verbose_name="تسک",
                    ),
                ),
            ],
            options={
                "verbose_name": "ردیف گزارش",
                "verbose_name_plural": "ردیف\u200cهای گزارش",
                "ordering": ["order", "id"],
            },
        ),
    ]
