# Generated by Django 5.2.17 on 2026-08-08 21:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_phone_role"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-created_at"],
                "verbose_name": "گزارش",
                "verbose_name_plural": "گزارش\u200cها",
            },
        ),
        migrations.AlterModelManagers(
            name="report",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.organization",
                verbose_name="سازمان",
            ),
        ),
    ]
