# Generated by Django 5.2.17 on 2026-08-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_invoice_invoiceline_and_more"),
        ("reports", "0002_alter_report_options_alter_report_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="finance.invoice",
                verbose_name="فاکتور",
            ),
        ),
    ]
