# Generated by Django 5.2.17 on 2026-09-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_report_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="content_hourly_rate",
            field=models.BigIntegerField(
                default=0, verbose_name="نرخِ ساعتیِ تولید محتوا (اسنپ\u200cشات)"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="content_word_rate",
            field=models.BigIntegerField(
                default=0, verbose_name="نرخِ هر کلمهٔ تولید محتوا (اسنپ\u200cشات)"
            ),
        ),
        migrations.CreateModel(
            name="ReportKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(max_length=200, verbose_name="کلمهٔ کلیدی"),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=30, verbose_name="جایگاه"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="reports.report",
                        verbose_name="گزارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلمهٔ کلیدیِ گزارش",
                "verbose_name_plural": "کلماتِ کلیدیِ گزارش",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="reports.report",
                        verbose_name="گزارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "سکشنِ گزارش",
                "verbose_name_plural": "سکشن\u200cهای گزارش",
                "ordering": ["order", "id"],
            },
        ),
    ]
