# Generated by Django 5.2.17 on 2026-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0004_report_content_hourly_rate_report_content_word_rate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="receipts/",
                verbose_name="رسیدِ پرداخت",
            ),
        ),
    ]
