# Generated by Django 5.2.17 on 2026-09-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleagues", "0004_colleague_birth_date_colleague_worktracker_username"),
        ("reports", "0005_report_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportitem",
            name="override_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="colleagues.colleague",
                verbose_name="مسئول (override)",
            ),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="override_estimate",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="زمان به دقیقه (override)"
            ),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="override_word_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="تعداد کلمه (override)"
            ),
        ),
    ]
