# Generated by Django 5.2.17 on 2026-09-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_reportitem_override_assignee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="public_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=16,
                null=True,
                unique=True,
                verbose_name="کدِ عمومی",
            ),
        ),
    ]
