# Generated by Django 5.2.17 on 2026-09-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_backfill_public_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportkeyword",
            name="change",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="تغییر جایگاه"
            ),
        ),
        migrations.AddField(
            model_name="reportkeyword",
            name="note",
            field=models.CharField(blank=True, max_length=200, verbose_name="یادداشت"),
        ),
        migrations.AlterField(
            model_name="reportkeyword",
            name="position",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="جایگاه فعلی"
            ),
        ),
    ]
