# Generated by Django 5.2.17 on 2026-08-06 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Colleague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "roles",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نقش\u200cها"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/colleagues/",
                        verbose_name="آواتار",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4183F2", max_length=7, verbose_name="رنگ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="تلفن"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "فعال"), ("inactive", "غیرفعال")],
                        default="active",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان غیرفعال\u200cسازی"
                    ),
                ),
                (
                    "join_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ عضویت"),
                ),
                (
                    "rate_per_word",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="دستمزد هر کلمه",
                    ),
                ),
                (
                    "rate_per_task",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="دستمزد هر تسک",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colleague",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "همکار",
                "verbose_name_plural": "همکاران",
                "ordering": ["status", "full_name"],
            },
        ),
    ]
