# Generated by Django 5.2.17 on 2026-08-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "colleagues",
            "0002_alter_colleague_options_alter_colleague_managers_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colleague",
            name="rate_per_task",
        ),
        migrations.RemoveField(
            model_name="colleague",
            name="rate_per_word",
        ),
        migrations.AddField(
            model_name="colleague",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="colleagues.colleague",
                verbose_name="مدیر",
            ),
        ),
        migrations.AddField(
            model_name="colleague",
            name="needs_review",
            field=models.BooleanField(
                default=False,
                help_text="فقط با تعیینِ مدیر معنا دارد؛ تسک\u200cهای انجام\u200cشده برای تاییدِ مدیرش به «بازبینی تسک» می\u200cرود.",
                verbose_name="تسک\u200cهایش نیاز به بازبینی دارد",
            ),
        ),
    ]
