# Generated by Django 5.2.17 on 2026-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleagues", "0003_remove_colleague_rate_per_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colleague",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
        migrations.AddField(
            model_name="colleague",
            name="worktracker_username",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="اتصال به حضورغیاب (نام کاربری worktracker)",
            ),
        ),
    ]
