# Generated by Django 5.2.17 on 2026-10-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleagues", "0004_colleague_birth_date_colleague_worktracker_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colleague",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["status", "hide_in_task_manager", "full_name"],
                "verbose_name": "همکار",
                "verbose_name_plural": "همکاران",
            },
        ),
        migrations.AddField(
            model_name="colleague",
            name="hide_in_task_manager",
            field=models.BooleanField(
                default=False,
                help_text="برای افرادی که فقط برای حسابداری/حقوق ثبت شده\u200cاند: از دراپ\u200cداون\u200cهای تسک\u200cمنیجر حذف و در فهرست افراد پایین\u200cتر نشان داده می\u200cشوند.",
                verbose_name="غیرفعال در تسک\u200cمنیجر",
            ),
        ),
    ]
