# Generated by Django 5.2.17 on 2026-08-06 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleagues", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("publish", "انتشار"),
                            ("update", "آپدیت"),
                            ("tech", "فنی"),
                            ("reportage", "رپورتاژ"),
                            ("linkbuilding", "لینک\u200cسازی"),
                            ("other", "سایر"),
                        ],
                        default="publish",
                        max_length=20,
                        verbose_name="نوع تسک",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        blank=True,
                        choices=[("minor", "سطحی"), ("major", "اساسی")],
                        max_length=10,
                        verbose_name="زیرنوع آپدیت",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("planned_date", models.DateField(verbose_name="تاریخ برنامه")),
                (
                    "planned_time",
                    models.TimeField(default="08:00", verbose_name="ساعت"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "در انتظار"),
                            ("doing", "در حال انجام"),
                            ("done", "انجام شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="todo",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "done_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ انجام"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "کم"), ("med", "متوسط"), ("high", "زیاد")],
                        default="med",
                        max_length=6,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد کلمه"
                    ),
                ),
                ("keywords", models.TextField(blank=True, verbose_name="کلمات کلیدی")),
                (
                    "lsi_keywords",
                    models.TextField(blank=True, verbose_name="کلمات LSI"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "current_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="جایگاه فعلی"
                    ),
                ),
                (
                    "target_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="جایگاه هدف"
                    ),
                ),
                (
                    "published_url",
                    models.URLField(blank=True, verbose_name="لینک انتشار"),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, verbose_name="آدرس مطلب فعلی"),
                ),
                (
                    "media_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام رسانه"
                    ),
                ),
                (
                    "media_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=14,
                        null=True,
                        verbose_name="هزینه رپورتاژ",
                    ),
                ),
                (
                    "anchor_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="انکر تکست"
                    ),
                ),
                ("target_url", models.URLField(blank=True, verbose_name="لینک مقصد")),
                (
                    "link_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("comment", "کامنت"),
                            ("profile", "پروفایل"),
                            ("forum", "فروم"),
                            ("directory", "دایرکتوری"),
                            ("social", "سوشال"),
                            ("other", "سایر"),
                        ],
                        max_length=12,
                        verbose_name="نوع لینک",
                    ),
                ),
                (
                    "link_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد لینک"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "بررسی\u200cنشده"),
                            ("approved", "تایید"),
                            ("needs_fix", "نیاز به اصلاح"),
                        ],
                        default="unreviewed",
                        max_length=12,
                        verbose_name="وضعیت بازبینی",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, verbose_name="یادداشت بازبینی"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بازبینی"
                    ),
                ),
                (
                    "ai_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="بررسی هوش مصنوعی"
                    ),
                ),
                (
                    "ai_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="امتیاز AI"
                    ),
                ),
                (
                    "ai_report",
                    models.JSONField(blank=True, null=True, verbose_name="گزارش AI"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="colleagues.colleague",
                        verbose_name="مسئول",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بازبین",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسک",
                "verbose_name_plural": "تسک\u200cها",
                "ordering": ["planned_date", "planned_time"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                        verbose_name="تسک",
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت تسک",
                "verbose_name_plural": "کامنت\u200cهای تسک",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status", "planned_date"],
                name="tasks_task_project_ec734b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "status", "done_date"],
                name="tasks_task_assigne_fa7490_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "planned_date"], name="tasks_task_status_af6f50_idx"
            ),
        ),
    ]
