# Generated by Django 5.2.17 on 2026-08-06 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="planned_time",
            field=models.TimeField(default=datetime.time(8, 0), verbose_name="ساعت"),
        ),
    ]
