# Generated by Django 5.2.17 on 2026-08-07 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_planned_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="custom",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="فیلدهای سفارشی"
            ),
        ),
        migrations.CreateModel(
            name="TaskTypeDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="نام نوع"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4183F2", max_length=7, verbose_name="رنگ"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="آیکن (اموجی)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع تسک سفارشی",
                "verbose_name_plural": "انواع تسک سفارشی",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="type_def",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.tasktypedef",
                verbose_name="نوع سفارشی",
            ),
        ),
        migrations.CreateModel(
            name="TaskTypeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(blank=True, max_length=40, verbose_name="کلید"),
                ),
                ("label", models.CharField(max_length=120, verbose_name="برچسب")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "متن کوتاه"),
                            ("textarea", "متن بلند"),
                            ("number", "عدد"),
                            ("checkbox", "چک\u200cباکس"),
                            ("select", "انتخابی"),
                            ("url", "لینک"),
                            ("date", "تاریخ"),
                        ],
                        default="text",
                        max_length=12,
                        verbose_name="نوع فیلد",
                    ),
                ),
                (
                    "options",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="گزینه\u200cها (با ویرگول)",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=120, verbose_name="راهنما"),
                ),
                ("required", models.BooleanField(default=False, verbose_name="اجباری")),
                (
                    "show_to_client",
                    models.BooleanField(default=True, verbose_name="نمایش به مشتری"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "type_def",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="tasks.tasktypedef",
                        verbose_name="نوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "فیلد نوع تسک",
                "verbose_name_plural": "فیلدهای نوع تسک",
                "ordering": ["order", "id"],
            },
        ),
    ]
