# Generated by Django 5.2.17 on 2026-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_custom_tasktypedef_task_type_def_tasktypefield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="target_rank",
        ),
        migrations.AddField(
            model_name="task",
            name="estimate_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="تخمین زمان (دقیقه)"
            ),
        ),
    ]
