# Generated by Django 5.2.17 on 2026-08-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_task_target_rank_task_estimate_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktypedef",
            name="builtin_key",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="کلید built-in"
            ),
        ),
    ]
