# Generated by Django 5.2.17 on 2026-08-08 16:15

from django.db import migrations, models


def cancelled_to_todo(apps, schema_editor):
    """وضعیت «لغو شده» حذف شد؛ تسک‌های قبلیِ لغوشده به «در انتظار» برمی‌گردند
    تا وضعیت یتیم (بدون انتخاب معتبر) نماند."""
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(status="cancelled").update(status="todo")


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_tasktypedef_builtin_key"),
    ]

    operations = [
        migrations.RunPython(cancelled_to_todo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "در انتظار"),
                    ("doing", "در حال انجام"),
                    ("done", "انجام شده"),
                ],
                default="todo",
                max_length=12,
                verbose_name="وضعیت",
            ),
        ),
    ]
