# Generated by Django 5.2.17 on 2026-08-08 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskReviewNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="یادداشت نیاز به اصلاح")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بازبین",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_notes",
                        to="tasks.task",
                        verbose_name="تسک",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشت بازبینی تسک",
                "verbose_name_plural": "یادداشت\u200cهای بازبینی تسک",
                "ordering": ["-created_at"],
            },
        ),
    ]
