# Generated by Django 5.2.17 on 2026-08-08 21:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_phone_role"),
        ("tasks", "0007_taskreviewnote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["planned_date", "planned_time"],
                "verbose_name": "تسک",
                "verbose_name_plural": "تسک\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="tasktypedef",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["order", "name"],
                "verbose_name": "نوع تسک سفارشی",
                "verbose_name_plural": "انواع تسک سفارشی",
            },
        ),
        migrations.AlterModelManagers(
            name="task",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tasktypedef",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.organization",
                verbose_name="سازمان",
            ),
        ),
        migrations.AddField(
            model_name="tasktypedef",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.organization",
                verbose_name="سازمان",
            ),
        ),
        migrations.AlterField(
            model_name="tasktypedef",
            name="name",
            field=models.CharField(max_length=80, verbose_name="نام نوع"),
        ),
        migrations.AlterUniqueTogether(
            name="tasktypedef",
            unique_together={("organization", "name")},
        ),
    ]
