# Generated by Django 5.2.17 on 2026-08-08 21:34

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_stamp_orgs_seed_roles"),
        ("tasks", "0008_alter_task_options_alter_tasktypedef_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_placeholder",
            field=models.BooleanField(
                default=False, verbose_name="پیش\u200cنمای تکرار"
            ),
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "freq",
                    models.CharField(
                        choices=[
                            ("daily", "روزانه"),
                            ("weekly", "هفتگی"),
                            ("monthly", "ماهانه"),
                        ],
                        default="weekly",
                        max_length=8,
                        verbose_name="تکرار",
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(default=1, verbose_name="فاصله (هر N)"),
                ),
                (
                    "weekdays",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="روزهای هفته"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="شروع")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد کل"
                    ),
                ),
                (
                    "skip_holidays",
                    models.BooleanField(default=True, verbose_name="رد کردن تعطیلات"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="سازمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعده تکرار",
                "verbose_name_plural": "قواعد تکرار",
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.recurrencerule",
                verbose_name="قاعده تکرار",
            ),
        ),
        migrations.CreateModel(
            name="TaskTypeKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=10, verbose_name="حداکثر امتیاز"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "has_checklist",
                    models.BooleanField(default=False, verbose_name="چک\u200cلیستی"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "type_def",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="tasks.tasktypedef",
                        verbose_name="نوع تسک",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI نوع تسک",
                "verbose_name_plural": "KPIهای نوع تسک",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="KPIChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="عنوان")),
                (
                    "score",
                    models.PositiveIntegerField(default=0, verbose_name="امتیاز"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tasks.tasktypekpi",
                        verbose_name="KPI",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم چک\u200cلیست KPI",
                "verbose_name_plural": "آیتم\u200cهای چک\u200cلیست KPI",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskKPIScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=0, verbose_name="امتیاز"),
                ),
                (
                    "checked_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="آیتم\u200cهای تیک\u200cخورده",
                    ),
                ),
                (
                    "scored_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان امتیاز"),
                ),
                (
                    "scored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بازبین",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_scores",
                        to="tasks.task",
                        verbose_name="تسک",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="tasks.tasktypekpi",
                        verbose_name="KPI",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز KPI تسک",
                "verbose_name_plural": "امتیازهای KPI تسک",
                "unique_together": {("task", "kpi")},
            },
        ),
    ]
