# Generated by Django 5.2.17 on 2026-08-09 14:49

from django.db import migrations, models


def default_content_review(apps, schema_editor):
    """انواعِ محتوایی (انتشار/آپدیت/رپورتاژ) به‌طور پیش‌فرض نیاز به بازبینی دارند
    تا رفتارِ قبلیِ صفحه‌ی بازبینی حفظ شود."""
    TaskTypeDef = apps.get_model("tasks", "TaskTypeDef")
    TaskTypeDef.objects.filter(
        builtin_key__in=["publish", "update", "reportage"]).update(requires_review=True)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_task_is_placeholder_recurrencerule_task_recurrence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktypedef",
            name="requires_review",
            field=models.BooleanField(
                default=False, verbose_name="نیاز به بازبینی دارد"
            ),
        ),
        migrations.RunPython(default_content_review, migrations.RunPython.noop),
    ]
