# Generated by Django 5.2.17 on 2026-08-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_tasktypedef_requires_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktypefield",
            name="is_word_source",
            field=models.BooleanField(default=False, verbose_name="منبعِ تعداد کلمه"),
        ),
    ]
