# Generated by Django 5.2.17 on 2026-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_tasktypefield_is_word_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="spent_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="زمان کارکرد (دقیقه)"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="timer_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="شروع تایمر جاری"
            ),
        ),
    ]
