# Generated by Django 5.2.17 on 2026-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_task_spent_minutes_task_timer_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="quality_score",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="امتیاز کیفیت (بدون KPI)"
            ),
        ),
    ]
