# Generated by Django 5.2.17 on 2026-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_task_quality_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="needs_review",
            field=models.BooleanField(default=False, verbose_name="نیاز به بازبینی"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "در انتظار"),
                    ("doing", "در حال انجام"),
                    ("pending", "تکمیل — در انتظار بازبینی"),
                    ("done", "انجام شده"),
                ],
                default="todo",
                max_length=12,
                verbose_name="وضعیت",
            ),
        ),
    ]
