# Generated by Django 5.2.17 on 2026-08-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_task_deleted_at_task_deleted_by_taskhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="report_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "فروردین"),
                    (2, "اردیبهشت"),
                    (3, "خرداد"),
                    (4, "تیر"),
                    (5, "مرداد"),
                    (6, "شهریور"),
                    (7, "مهر"),
                    (8, "آبان"),
                    (9, "آذر"),
                    (10, "دی"),
                    (11, "بهمن"),
                    (12, "اسفند"),
                ],
                db_index=True,
                null=True,
                verbose_name="ماه گزارش",
            ),
        ),
    ]
