# Generated by Django 5.2.17 on 2026-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_task_report_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktypefield",
            name="is_keyword_source",
            field=models.BooleanField(
                default=False, verbose_name="حاویِ کلمهٔ کلیدیِ قابل\u200cجستجو"
            ),
        ),
        migrations.AddField(
            model_name="tasktypefield",
            name="is_link_source",
            field=models.BooleanField(
                default=False, verbose_name="حاویِ لینکِ هدفِ قابل\u200cجستجو"
            ),
        ),
        migrations.AddField(
            model_name="tasktypefield",
            name="is_page_link",
            field=models.BooleanField(
                default=False, verbose_name="لینکِ صفحهٔ خودِ همین تسک"
            ),
        ),
        migrations.AddField(
            model_name="tasktypefield",
            name="required_on_done",
            field=models.BooleanField(
                default=False, verbose_name="اجباری فقط برای تکمیل"
            ),
        ),
        migrations.AddField(
            model_name="tasktypefield",
            name="track_keyword_rank",
            field=models.BooleanField(
                default=False, verbose_name="رتبهٔ این کلمه ردیابی شود"
            ),
        ),
        migrations.AlterField(
            model_name="tasktypefield",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "متن کوتاه"),
                    ("textarea", "متن بلند"),
                    ("number", "عدد"),
                    ("checkbox", "چک\u200cباکس"),
                    ("select", "انتخابی"),
                    ("url", "لینک"),
                    ("date", "تاریخ"),
                    ("tags", "چندتایی (کلمه + اینتر)"),
                ],
                default="text",
                max_length=12,
                verbose_name="نوع فیلد",
            ),
        ),
        migrations.AlterField(
            model_name="tasktypefield",
            name="required",
            field=models.BooleanField(default=False, verbose_name="اجباری (همیشه)"),
        ),
    ]
