# Generated by Django 5.2.17 on 2026-08-17 09:26

from django.db import migrations, models


def backfill_report_year(apps, schema_editor):
    """تسک‌هایی که ماهِ گزارش دارند ولی سال ندارند → سالِ جالیِ تاریخِ برنامه
    (یا تاریخِ ساخت). تا نمایشِ «مرداد ۱۴۰۵» برای دادهٔ قدیمی هم سال داشته باشد."""
    from core.jalali import g2j

    Task = apps.get_model("tasks", "Task")
    for t in Task.objects.filter(report_month__isnull=False, report_year__isnull=True).iterator():
        d = t.planned_date or (t.created_at.date() if t.created_at else None)
        if d:
            t.report_year = g2j(d).year
            t.save(update_fields=["report_year"])


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_tasktypefield_is_keyword_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="report_year",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True, verbose_name="سالِ گزارش"
            ),
        ),
        migrations.RunPython(backfill_report_year, migrations.RunPython.noop),
    ]
