# Generated by Django 5.2.17 on 2026-08-17 13:43

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_membership_role"),
        ("projects", "0006_backfill_personal_projects"),
        ("tasks", "0018_task_report_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="board_order",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="ترتیبِ برد"
            ),
        ),
        migrations.CreateModel(
            name="ReportMonthStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="سالِ گزارش")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "فروردین"),
                            (2, "اردیبهشت"),
                            (3, "خرداد"),
                            (4, "تیر"),
                            (5, "مرداد"),
                            (6, "شهریور"),
                            (7, "مهر"),
                            (8, "آبان"),
                            (9, "آذر"),
                            (10, "دی"),
                            (11, "بهمن"),
                            (12, "اسفند"),
                        ],
                        verbose_name="ماهِ گزارش",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="استراتژی")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="سازمان",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_strategies",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "استراتژیِ ماهِ گزارش",
                "verbose_name_plural": "استراتژی\u200cهای ماهِ گزارش",
                "ordering": ["-year", "-month"],
                "base_manager_name": "all_objects",
                "unique_together": {("project", "year", "month")},
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
