# Generated by Django 5.2.17 on 2026-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_task_board_order_reportmonthstrategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="planned_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ برنامه"),
        ),
    ]
