# Generated by Django 5.2.17 on 2026-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_reportperiod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportperiod",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["order", "-year", "-month"],
                "verbose_name": "ماهِ گزارش",
                "verbose_name_plural": "ماه\u200cهای گزارش",
            },
        ),
        migrations.AddField(
            model_name="reportperiod",
            name="order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="ترتیب"),
        ),
    ]
