# Generated by Django 5.2.17 on 2026-08-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_alter_reportperiod_options_reportperiod_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportmonthstrategy",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["order", "-year", "-month"],
                "verbose_name": "استراتژیِ ماهِ گزارش",
                "verbose_name_plural": "استراتژی\u200cهای ماهِ گزارش",
            },
        ),
        migrations.AddField(
            model_name="reportmonthstrategy",
            name="order",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="ترتیبِ سکشن"
            ),
        ),
    ]
