# Generated by Django 5.2.17 on 2026-08-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_alter_reportmonthstrategy_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="checklist",
            field=models.JSONField(
                blank=True, default=list, verbose_name="چک\u200cلیست"
            ),
        ),
    ]
