# Generated by Django 5.2.17 on 2026-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0024_task_checklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktypefield",
            name="width",
            field=models.CharField(
                choices=[
                    ("full", "تمام\u200cعرض"),
                    ("half", "نصف"),
                    ("third", "یک\u200cسوم"),
                    ("quarter", "یک\u200cچهارم"),
                ],
                default="full",
                max_length=8,
                verbose_name="عرض در مودال",
            ),
        ),
    ]
