# Generated by Django 5.2.17 on 2026-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0025_tasktypefield_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="timer_heartbeat",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ضربانِ تایمر"
            ),
        ),
    ]
