# Generated by Django 5.2.17 on 2026-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0029_reportage_track_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="kpi_self_checks",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="خوداظهاریِ چک\u200cلیستِ KPI"
            ),
        ),
    ]
