# Generated by Django 5.2.17 on 2026-08-23 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("start_date", models.DateField(verbose_name="شروع")),
                ("end_date", models.DateField(verbose_name="پایان")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "هدف",
                "verbose_name_plural": "اهداف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "weekdays",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="روزهای هفته"
                    ),
                ),
                (
                    "polarity",
                    models.CharField(
                        choices=[("good", "مثبت"), ("bad", "منفی")],
                        default="good",
                        max_length=4,
                        verbose_name="قطبیت",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.IntegerField(db_index=True, default=0, verbose_name="ترتیب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عادت",
                "verbose_name_plural": "عادت\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("note", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "kind",
                    models.CharField(blank=True, max_length=40, verbose_name="نوع"),
                ),
                (
                    "week_start",
                    models.DateField(db_index=True, verbose_name="شنبه\u200cی هفته"),
                ),
                (
                    "planned_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاریخِ برنامه",
                    ),
                ),
                (
                    "done",
                    models.BooleanField(default=False, verbose_name="انجام\u200cشده"),
                ),
                (
                    "playing",
                    models.BooleanField(default=False, verbose_name="در حالِ اجرا"),
                ),
                (
                    "order",
                    models.IntegerField(db_index=True, default=0, verbose_name="ترتیب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ویرایش"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تسک شخصی",
                "verbose_name_plural": "تسک\u200cهای شخصی",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "done",
                    models.BooleanField(default=True, verbose_name="رعایت\u200cشده"),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="personal.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگِ عادت",
                "verbose_name_plural": "لاگ\u200cهای عادت",
                "unique_together": {("habit", "date")},
            },
        ),
    ]
