# Generated by Django 5.2.17 on 2026-08-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonalTask",
        ),
    ]
