# Generated by Django 5.2.17 on 2026-08-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0003_dailyplan"),
        ("tasks", "0024_task_checklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="color",
            field=models.CharField(default="#6366F1", max_length=7, verbose_name="رنگ"),
        ),
        migrations.CreateModel(
            name="GoalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(db_index=True, default=0, verbose_name="ترتیب"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="personal.goal",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_link",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "وصلِ تسک به هدف",
                "verbose_name_plural": "وصل\u200cهای تسک به هدف",
                "ordering": ["order", "id"],
            },
        ),
    ]
