# Generated by Django 5.2.17 on 2026-08-10 20:02

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_stamp_orgs_seed_roles"),
        ("projects", "0003_project_track_keyword_rank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                ("page_url", models.URLField(max_length=500, verbose_name="لینک صفحه")),
                (
                    "keyword",
                    models.CharField(max_length=255, verbose_name="کلمه کلیدی"),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False, verbose_name="دستی (از مودالِ صفحات مهم)"
                    ),
                ),
                (
                    "is_starred",
                    models.BooleanField(
                        default=False, verbose_name="مهم (ستاره\u200cدار)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                        verbose_name="سازمان",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_keywords",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلمه\u200cی کلیدیِ ردیابی\u200cشده",
                "verbose_name_plural": "کلمات کلیدیِ ردیابی\u200cشده",
                "ordering": ["-is_starred", "keyword"],
                "base_manager_name": "all_objects",
                "unique_together": {("project", "page_url", "keyword")},
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="KeywordRankSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("position", models.PositiveIntegerField(verbose_name="جایگاه")),
                (
                    "seen_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        verbose_name="لینکِ دیده\u200cشده در نتیجه",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="seo.trackedkeyword",
                        verbose_name="کلمه کلیدی",
                    ),
                ),
            ],
            options={
                "verbose_name": "رکورد جایگاه",
                "verbose_name_plural": "رکوردهای جایگاه",
                "ordering": ["date"],
                "unique_together": {("keyword", "date")},
            },
        ),
    ]
